// Code generated by protoc-gen-go. DO NOT EDIT.
// source: die.proto

package dice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Die struct {
	Type                 string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Size                 int32       `protobuf:"zigzag32,2,opt,name=size,proto3" json:"size,omitempty"`
	Result               *Result     `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Rolls                []*Result   `protobuf:"bytes,5,rep,name=rolls,proto3" json:"rolls,omitempty"`
	Modifiers            []*Modifier `protobuf:"bytes,6,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Die) Reset()         { *m = Die{} }
func (m *Die) String() string { return proto.CompactTextString(m) }
func (*Die) ProtoMessage()    {}
func (*Die) Descriptor() ([]byte, []int) {
	return fileDescriptor_63024141677a1298, []int{0}
}

func (m *Die) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Die.Unmarshal(m, b)
}
func (m *Die) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Die.Marshal(b, m, deterministic)
}
func (m *Die) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Die.Merge(m, src)
}
func (m *Die) XXX_Size() int {
	return xxx_messageInfo_Die.Size(m)
}
func (m *Die) XXX_DiscardUnknown() {
	xxx_messageInfo_Die.DiscardUnknown(m)
}

var xxx_messageInfo_Die proto.InternalMessageInfo

func (m *Die) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Die) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Die) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Die) GetRolls() []*Result {
	if m != nil {
		return m.Rolls
	}
	return nil
}

func (m *Die) GetModifiers() []*Modifier {
	if m != nil {
		return m.Modifiers
	}
	return nil
}

type Properties struct {
	Type                 string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Size                 int32       `protobuf:"zigzag32,2,opt,name=size,proto3" json:"size,omitempty"`
	Result               *Result     `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Count                int32       `protobuf:"zigzag32,4,opt,name=count,proto3" json:"count,omitempty"`
	DieModifiers         []*Modifier `protobuf:"bytes,5,rep,name=die_modifiers,json=dieModifiers,proto3" json:"die_modifiers,omitempty"`
	GroupModifiers       []*Modifier `protobuf:"bytes,6,rep,name=group_modifiers,json=groupModifiers,proto3" json:"group_modifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Properties) Reset()         { *m = Properties{} }
func (m *Properties) String() string { return proto.CompactTextString(m) }
func (*Properties) ProtoMessage()    {}
func (*Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_63024141677a1298, []int{1}
}

func (m *Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Properties.Unmarshal(m, b)
}
func (m *Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Properties.Marshal(b, m, deterministic)
}
func (m *Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Properties.Merge(m, src)
}
func (m *Properties) XXX_Size() int {
	return xxx_messageInfo_Properties.Size(m)
}
func (m *Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_Properties proto.InternalMessageInfo

func (m *Properties) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Properties) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Properties) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Properties) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Properties) GetDieModifiers() []*Modifier {
	if m != nil {
		return m.DieModifiers
	}
	return nil
}

func (m *Properties) GetGroupModifiers() []*Modifier {
	if m != nil {
		return m.GroupModifiers
	}
	return nil
}

func init() {
	proto.RegisterType((*Die)(nil), "dice.Die")
	proto.RegisterType((*Properties)(nil), "dice.Properties")
}

func init() { proto.RegisterFile("die.proto", fileDescriptor_63024141677a1298) }

var fileDescriptor_63024141677a1298 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0xc9, 0xd7, 0x3f, 0xd0, 0xfb, 0xd5, 0xca, 0x04, 0x17, 0xa1, 0xab, 0x52, 0x5c, 0x74,
	0xa1, 0x1d, 0x70, 0x16, 0xee, 0xc5, 0xad, 0x20, 0x59, 0xba, 0x19, 0x9c, 0xe6, 0x5a, 0x2f, 0x74,
	0x4c, 0x49, 0x52, 0x41, 0xdf, 0xc7, 0xd7, 0xf2, 0x59, 0xa4, 0xc9, 0x8c, 0xb3, 0x50, 0x14, 0xdc,
	0xdd, 0x73, 0xee, 0x39, 0xe4, 0x77, 0x09, 0x64, 0x8a, 0xb0, 0x1d, 0x8d, 0x76, 0x9a, 0xc7, 0x8a,
	0x3a, 0x2c, 0x8b, 0xad, 0x56, 0xf4, 0x40, 0x68, 0x82, 0x5b, 0xe6, 0x06, 0xed, 0x34, 0xb8, 0xa0,
	0xea, 0x37, 0x06, 0xd1, 0x35, 0x21, 0xe7, 0x10, 0xbb, 0x97, 0x11, 0x05, 0xab, 0x58, 0x93, 0x49,
	0x3f, 0xcf, 0x9e, 0xa5, 0x57, 0x14, 0xff, 0x2a, 0xd6, 0x2c, 0xa4, 0x9f, 0xf9, 0x29, 0xa4, 0xa1,
	0x2f, 0xe2, 0x8a, 0x35, 0xff, 0x2f, 0xf2, 0x76, 0x7e, 0xa4, 0x95, 0xde, 0x93, 0xbb, 0x1d, 0xaf,
	0x21, 0x31, 0x7a, 0x18, 0xac, 0x48, 0xaa, 0xe8, 0x4b, 0x28, 0xac, 0xf8, 0x19, 0x64, 0x7b, 0x32,
	0x2b, 0x52, 0x9f, 0x2b, 0x42, 0xee, 0x66, 0x67, 0xcb, 0x43, 0xa0, 0x7e, 0x67, 0x00, 0xb7, 0x46,
	0x8f, 0x68, 0x1c, 0xa1, 0xfd, 0x03, 0x6e, 0xf4, 0x03, 0xee, 0x09, 0x24, 0x9d, 0x9e, 0x9e, 0xc2,
	0x4d, 0x0b, 0x19, 0x04, 0x5f, 0xc1, 0x91, 0x22, 0x5c, 0x1f, 0x20, 0x93, 0x6f, 0x21, 0x73, 0x45,
	0xb8, 0x17, 0x96, 0x5f, 0xc2, 0x71, 0x6f, 0xf4, 0x34, 0xae, 0x7f, 0xbb, 0xad, 0xf0, 0xb1, 0xcf,
	0xe2, 0x55, 0x79, 0x27, 0x7a, 0x72, 0x8f, 0xd3, 0xa6, 0xed, 0xf4, 0x76, 0xe9, 0xcc, 0xfd, 0x33,
	0xd9, 0xf3, 0x7e, 0x39, 0x97, 0x36, 0xa9, 0xff, 0xab, 0xd5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x72, 0xd8, 0x27, 0xb2, 0xdc, 0x01, 0x00, 0x00,
}
