// Code generated by protoc-gen-go. DO NOT EDIT.
// source: die.proto

package dice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DieType is the enum of types that a die or dice can be.
type DieType int32

const (
	DieType_STANDARD_POLYHEDRON DieType = 0
	DieType_FUDGE               DieType = 1
	DieType_INDEX               DieType = 2
)

var DieType_name = map[int32]string{
	0: "STANDARD_POLYHEDRON",
	1: "FUDGE",
	2: "INDEX",
}

var DieType_value = map[string]int32{
	"STANDARD_POLYHEDRON": 0,
	"FUDGE":               1,
	"INDEX":               2,
}

func (x DieType) String() string {
	return proto.EnumName(DieType_name, int32(x))
}

func (DieType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63024141677a1298, []int{0}
}

type Die struct {
	Type DieType `protobuf:"varint,1,opt,name=type,proto3,enum=dice.DieType" json:"type,omitempty"`
	// Types that are valid to be assigned to DieCoreProperty:
	//	*Die_Size
	DieCoreProperty      isDie_DieCoreProperty `protobuf_oneof:"die_core_property"`
	Result               *Result               `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Rolls                []*Result             `protobuf:"bytes,5,rep,name=rolls,proto3" json:"rolls,omitempty"`
	Modifiers            []*Modifier           `protobuf:"bytes,6,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Die) Reset()         { *m = Die{} }
func (m *Die) String() string { return proto.CompactTextString(m) }
func (*Die) ProtoMessage()    {}
func (*Die) Descriptor() ([]byte, []int) {
	return fileDescriptor_63024141677a1298, []int{0}
}

func (m *Die) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Die.Unmarshal(m, b)
}
func (m *Die) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Die.Marshal(b, m, deterministic)
}
func (m *Die) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Die.Merge(m, src)
}
func (m *Die) XXX_Size() int {
	return xxx_messageInfo_Die.Size(m)
}
func (m *Die) XXX_DiscardUnknown() {
	xxx_messageInfo_Die.DiscardUnknown(m)
}

var xxx_messageInfo_Die proto.InternalMessageInfo

func (m *Die) GetType() DieType {
	if m != nil {
		return m.Type
	}
	return DieType_STANDARD_POLYHEDRON
}

type isDie_DieCoreProperty interface {
	isDie_DieCoreProperty()
}

type Die_Size struct {
	Size int32 `protobuf:"zigzag32,2,opt,name=size,proto3,oneof"`
}

func (*Die_Size) isDie_DieCoreProperty() {}

func (m *Die) GetDieCoreProperty() isDie_DieCoreProperty {
	if m != nil {
		return m.DieCoreProperty
	}
	return nil
}

func (m *Die) GetSize() int32 {
	if x, ok := m.GetDieCoreProperty().(*Die_Size); ok {
		return x.Size
	}
	return 0
}

func (m *Die) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Die) GetRolls() []*Result {
	if m != nil {
		return m.Rolls
	}
	return nil
}

func (m *Die) GetModifiers() []*Modifier {
	if m != nil {
		return m.Modifiers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Die) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Die_Size)(nil),
	}
}

type Properties struct {
	Type                 DieType     `protobuf:"varint,1,opt,name=type,proto3,enum=dice.DieType" json:"type,omitempty"`
	Size                 int32       `protobuf:"zigzag32,2,opt,name=size,proto3" json:"size,omitempty"`
	Result               *Result     `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Count                int32       `protobuf:"zigzag32,4,opt,name=count,proto3" json:"count,omitempty"`
	DieModifiers         []*Modifier `protobuf:"bytes,5,rep,name=die_modifiers,json=dieModifiers,proto3" json:"die_modifiers,omitempty"`
	GroupModifiers       []*Modifier `protobuf:"bytes,6,rep,name=group_modifiers,json=groupModifiers,proto3" json:"group_modifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Properties) Reset()         { *m = Properties{} }
func (m *Properties) String() string { return proto.CompactTextString(m) }
func (*Properties) ProtoMessage()    {}
func (*Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_63024141677a1298, []int{1}
}

func (m *Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Properties.Unmarshal(m, b)
}
func (m *Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Properties.Marshal(b, m, deterministic)
}
func (m *Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Properties.Merge(m, src)
}
func (m *Properties) XXX_Size() int {
	return xxx_messageInfo_Properties.Size(m)
}
func (m *Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_Properties proto.InternalMessageInfo

func (m *Properties) GetType() DieType {
	if m != nil {
		return m.Type
	}
	return DieType_STANDARD_POLYHEDRON
}

func (m *Properties) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Properties) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Properties) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Properties) GetDieModifiers() []*Modifier {
	if m != nil {
		return m.DieModifiers
	}
	return nil
}

func (m *Properties) GetGroupModifiers() []*Modifier {
	if m != nil {
		return m.GroupModifiers
	}
	return nil
}

func init() {
	proto.RegisterEnum("dice.DieType", DieType_name, DieType_value)
	proto.RegisterType((*Die)(nil), "dice.Die")
	proto.RegisterType((*Properties)(nil), "dice.Properties")
}

func init() { proto.RegisterFile("die.proto", fileDescriptor_63024141677a1298) }

var fileDescriptor_63024141677a1298 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4b, 0x02, 0x41,
	0x14, 0x85, 0x5d, 0xdd, 0x35, 0xbc, 0xe9, 0xa6, 0xa3, 0xd0, 0xe2, 0xd3, 0x26, 0x3d, 0x48, 0xd4,
	0x0a, 0xfa, 0x50, 0xaf, 0xca, 0x5a, 0x06, 0xa5, 0x32, 0x19, 0x54, 0x2f, 0x4b, 0xee, 0xde, 0x6c,
	0x40, 0x9b, 0x65, 0x66, 0x37, 0xb0, 0xbf, 0xd8, 0x6f, 0xe9, 0x3f, 0xc4, 0xee, 0x68, 0x06, 0x46,
	0xf5, 0x36, 0xe7, 0x9e, 0x73, 0x66, 0xee, 0x07, 0x03, 0x85, 0x80, 0xa1, 0x13, 0x0a, 0x1e, 0x71,
	0xa2, 0x07, 0xcc, 0xc7, 0xba, 0xb9, 0xe0, 0x01, 0x7b, 0x62, 0x28, 0xd4, 0xb4, 0x5e, 0x14, 0x28,
	0xe3, 0x79, 0xa4, 0x54, 0xe3, 0x5d, 0x83, 0x9c, 0xcb, 0x90, 0x1c, 0x80, 0x1e, 0x2d, 0x43, 0xb4,
	0x34, 0x5b, 0x6b, 0x9a, 0xed, 0x92, 0x93, 0x54, 0x1d, 0x97, 0xe1, 0x64, 0x19, 0x22, 0x4d, 0x2d,
	0x52, 0x03, 0x5d, 0xb2, 0x37, 0xb4, 0xb2, 0xb6, 0xd6, 0xac, 0x0c, 0x32, 0x34, 0x55, 0xe4, 0x10,
	0xf2, 0xea, 0x42, 0x4b, 0xb7, 0xb5, 0xe6, 0x6e, 0xbb, 0xa8, 0xaa, 0x34, 0x9d, 0xd1, 0x95, 0x47,
	0x1a, 0x60, 0x08, 0x3e, 0x9f, 0x4b, 0xcb, 0xb0, 0x73, 0x5b, 0x21, 0x65, 0x91, 0x63, 0x28, 0xac,
	0x57, 0x95, 0x56, 0x3e, 0xcd, 0x99, 0x2a, 0x77, 0xbd, 0x1a, 0xd3, 0x4d, 0xa0, 0x57, 0x85, 0x4a,
	0xc0, 0xd0, 0xf3, 0xb9, 0x40, 0x2f, 0x14, 0x3c, 0x44, 0x11, 0x2d, 0x1b, 0x1f, 0x1a, 0xc0, 0x58,
	0x09, 0x86, 0xf2, 0x3f, 0x50, 0xe4, 0x3b, 0xd4, 0x16, 0x52, 0xee, 0x17, 0xa4, 0x1a, 0x18, 0x3e,
	0x8f, 0x5f, 0x14, 0x77, 0x85, 0x2a, 0x41, 0x3a, 0x50, 0x4a, 0xd6, 0xda, 0x80, 0x18, 0x3f, 0x82,
	0x14, 0x03, 0x86, 0x6b, 0x21, 0xc9, 0x29, 0xec, 0xcd, 0x04, 0x8f, 0x43, 0xef, 0x2f, 0x7e, 0x33,
	0x8d, 0x7d, 0x15, 0x8f, 0xce, 0x60, 0x67, 0x85, 0x43, 0xf6, 0xa1, 0x7a, 0x33, 0xe9, 0x0e, 0xdd,
	0x2e, 0x75, 0xbd, 0xf1, 0xe8, 0xea, 0x7e, 0xd0, 0x77, 0xe9, 0x68, 0x58, 0xce, 0x90, 0x02, 0x18,
	0xe7, 0xb7, 0xee, 0x45, 0xbf, 0xac, 0x25, 0xc7, 0xcb, 0xa1, 0xdb, 0xbf, 0x2b, 0x67, 0x7b, 0xf5,
	0x07, 0x6b, 0xc6, 0xa2, 0xe7, 0x78, 0xea, 0xf8, 0x7c, 0xd1, 0x8a, 0xc4, 0xe3, 0x2b, 0x93, 0x27,
	0xb3, 0x56, 0xf2, 0xdc, 0x34, 0x9f, 0x7e, 0x8d, 0xce, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x77, 0x2b, 0x53, 0x4b, 0x02, 0x00, 0x00,
}
